[package]
name = "rust_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.49.0", features = ["full"]}
axum = "0.7"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
reqwest = {version = "0.12", features = ["json"]}